Neos:
  Neos:
    fusion:
      autoInclude:
        Litespeed.Blockquote: true
    userInterface:
      translation:
        autoInclude:
          Litespeed.Blockquote:
            - 'NodeTypes/*'
    Ui:
      frontendConfiguration:
        'Carbon.CodePen':
          afx:
            fusionObjects:
              'Blockquote':
                documentation: Add a blockquote
                snippet: |
                  <Litespeed.Blockquote:Presentation.Blockquote
                    cite="${1}"
                    function="${2}"
                    ${3:class="${4}"}
                  >
                    ${5}
                  </Litespeed.Blockquote:Presentation.Blockquote>'
              'Blockquote.Image':
                documentation: Add a blockquote with image
                snippet: |
                  <Litespeed.Blockquote:Presentation.BlockquoteWithImage
                    image={asset[0]}
                    cite="${1}"
                    function="${2}"
                    theme="${3|main,minor,minor2,gray|}"}
                    ${4:class="${5}"}
                  >
                    ${5}
                  </Litespeed.Blockquote:Presentation.BlockquoteWithImage>
